#!/bin/sh

slstatus &
picom &
xautolock -time 10 -locker slock &
dunst &
fnlockctl &
fusuma &
syncthing &
udiskie &
mbpfan &



xrdb -merge .Xresources

#set the screen resolution
#xrandr --output eDP1 --primary --mode 1920x1200 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off &


nitrogen --restore

xmodmap .xmodmap


export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
wmname LG3D

#main loop

while true; do
    #source .profile
    # Log stderror to a file 
    dwm 2> ~/.dwm.log 
    #wallpaper $(cat ~/.curwall) -- NO!
    # No error logging
    #dwm >/dev/null 2>&1
done

